sudo: false
dist: xenial
language: python
cache: pip
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
services:
  - redis-server
install:
  - "if [[ $REDIS_VERSION == '3.0' ]]; then REDIS_VERSION=3.0 make redis-install; fi"
  - "if [[ $REDIS_VERSION == '3.2' ]]; then REDIS_VERSION=3.2 make redis-install; fi"
  - "if [[ $REDIS_VERSION == '4.0' ]]; then REDIS_VERSION=4.0 make redis-install; fi"
  - "if [[ $REDIS_VERSION == '5.0' ]]; then REDIS_VERSION=5.0 make redis-install; fi"
  - "if [[ $TEST_PYCODESTYLE == '1' ]]; then pip install pycodestyle; fi"
  - pip install -r dev-requirements.txt
  - pip install -e .
  - "if [[ $HIREDIS == '1' ]]; then pip install hiredis; fi"
  - "pip freeze | grep redis"
  - "pip freeze"
env:
  # Redis 3.0 & HIREDIS
  - HIREDIS=0 REDIS_VERSION=3.0
  - HIREDIS=1 REDIS_VERSION=3.0
  # Redis 3.2 & HIREDIS
  - HIREDIS=0 REDIS_VERSION=3.2
  - HIREDIS=1 REDIS_VERSION=3.2
  # Redis 4.0 & HIREDIS
  - HIREDIS=0 REDIS_VERSION=4.0
  - HIREDIS=1 REDIS_VERSION=4.0
  # Redis 5.0 & HIREDIS
  - HIREDIS=0 REDIS_VERSION=5.0
  - HIREDIS=1 REDIS_VERSION=5.0
script:
  - make start
  - coverage erase
  - coverage run --source rediscluster -p -m py.test
  - py.test
  - make stop
after_success:
  - coverage combine
  - coveralls
  - "if [[ $TEST_PYCODESTYLE == '1' ]]; then pycodestyle --repeat --show-source --exclude=.venv,.tox,dist,docs,build,*.egg,redis_install .; fi"
matrix:
  allow_failures:
    - python: "nightly"
    - python: 2.7
      env: TEST_PYCODESTYLE=1
    - python: 3.6
      env: TEST_PYCODESTYLE=1
    # python 3.7 has to be specified manually in the matrix
    # https://github.com/travis-ci/travis-ci/issues/9815
    - python: 3.7
      dist: xenial
      sudo: true
      env: TEST_HIREDIS=0
    - python: 3.7
      dist: xenial
      sudo: true
      env: TEST_HIREDIS=1
